### PR TITLE
Added note about tilde-expansion to README

### PR DESCRIPTION
**Pull request by abingham**
@ptrv Please review this and merge it in if it looks OK.

### CODE REVIEW

**Comment by ptrv** [comment]
Improving the docs is always good :smile: 

@abingham Shouldn't we rather expand the path? With `ycmd-server-command` we would need to add some logic to find out which element is the path in the list because it may also consist some other arguments, which wouldn't be so nice.

I started a branch a while ago to separate the python command and ycmd path and having backward compatibility with `ycmd-server-command` here https://github.com/ptrv/emacs-ycmd/tree/new-server-variables

Do you think it's worth to finish the feature?

**Comment by abingham** [comment]
@ptrv Right, I was too lazy to try to find a way to figure out which elements in the command should be treated as paths. If there's a robust way to do that, then I'd be happy to merge it in.

The approach you've tried of separating the command path from the arguments might be a reasonable approach. I can't think of any reason that it wouldn't work, though I am a bit concerned about making a chance that will break essentially every installation.

**Comment by ptrv** [comment]
The old variable is still supported and take in account if already set, so it would not break existing setups

**Comment by abingham** [comment]
Ah, I see...sorry, I was initially reading this thread on my phone, and that makes me lazy. The patch looks good to me if you want to merge it in. It would certainly save me some time by allowing me to use the exact same configuration across several machines!

**Pull request merged**
