### PR TITLE
Add support for /filter_and_sort_candidates request

### LINKED ISSUE #393: support for /filter_and_sort_candidates server request
Hi guys,

Is there any past or present reflexion about supporting the `/filter_and_sort_candidates` ycmd server command ?

Apparently it could be useful to get the fuzzy-matching and completion ranking for languages not explicitly supported by `ycmd`.

### PR DESCRIPTION
**Pull request by ptrv**
Resolves #393

### CODE REVIEW

**Comment by abingham** [comment]
@ptrv Any idea why the tests are failing for 24.3? It looks like the json encoding of the test data is running into problem. Does the encoder not accept a cons-pairs or something?

**Comment by ptrv** [comment]
I have no idea why the tests fail on Emacs 24.3. I need to investigate.

**Comment by abingham** [comment]
Would you prefer that I merge this in now and create a new issue for the
failing test? It's a new feature that nobody depends on, so it won't matter
too much if it's potentially broken on 24.3.

**Comment by ptrv** [comment]
Let's see if the issue can be fixed first before merging.

**Comment by ptrv** [comment]
the Emacs 24.3 version of `json-encode` fails to encode something like

``` emacs-lisp
'((a . (((a . b) (c . d))
        ((a . b) (c . d)))))
```

I disabled the test for Emacs versions < 24.4

**Pull request merged**
