### PR TITLE
Load extra conf file synchronously on UnknownExtraConf error

### PR DESCRIPTION
**Pull request by ptrv**
When we get an UnknownExtraConf error and our `ycmd-extra-conf-handler` is set to `ask`, we need to send the request synchronously before we call `(ycmd-notify-file-ready-to-parse)`, else we get the `y-o-n-p` popup multiple times.

### CODE REVIEW

**Comment by abingham** [comment]
How can I replicate the original issue?

**Comment by ptrv** [comment]
Load a file from a project whose file is not in the conf whitelist and set `ycmd-extra-conf-handler` to `ask`. Also `use-dialog-box` should be set to `t` in order to have a popup dialog presented.

**Comment by ptrv** [comment]
Also start GUI version of Emacs not from terminal.

**Comment by abingham** [comment]
Yeah, I tried that, but I only ever see the dialog once. I guess it must be
a bit of a race condition where the client sends more than one request to
the server before we tell the server to load the conf. In any case, if
you're seeing a problem then it's worth merging in.

**Comment by ptrv** [comment]
yes, the issue is a definately a race condition. The function `ycmd--handle-extra-conf-exception` was called twice on my machine.

The YCM vim plugin is also sending the `load_extra_conf` request synchronously.

**Comment by ptrv** [comment]
Thanks for merging!

**Pull request merged**
