### PR TITLE
Improve testsuite

### PR DESCRIPTION
**Pull request by ptrv**

### CODE REVIEW

**Comment by ptrv** [comment]
Now we need more tests :smile:

**Comment by abingham** [comment]
The only thing I would ask is that you update the README to include instructions for using your new command line invocation (i.e. `make test`). Also make a prominent note about the fact that ycmd and emacs-ycmd need to be siblings in the file structure.

**Comment by ptrv** [comment]
Of course, I will update the README

**Comment by ptrv** [comment]
@abingham Updated README and added ycmd path to Makefile

**Comment by abingham** [comment]
Awesome, thanks!

**Pull request merged**
