### PR TITLE
Avoid unnecessary pulse call, since pulse.el registers with next-error-hook

### PR DESCRIPTION
**Pull request by fischman**

### CODE REVIEW

**Comment by abingham** [comment]
Where does pulse.el register with `next-error-hook`? I've searched for `next-error` in the pulse.el that ships with 24.4, and I don't see anything like that.

**Comment by fischman** [comment]
@abingham: good question :)

The motivation for this pull request was that I noticed my next-error-hook had a bare pulse-line-hook-function in it, in addition to the ycmd-next-error-installed hook, so I assumed pulse.el was adding it.  Indeed, digging deeper it looks like my .emacs gets its pulse from cedet-1.1, where pulse.el would unconditionally add to next-error-hook  (done since pulse.el was added to cedet in http://sourceforge.net/p/cedet/git/ci/30498592/), but the copy of pulse.el that made it into the cedet in the emacs repository looks to not have that, and cedet has since lost the same code in a "sync with emacs" (http://sourceforge.net/p/cedet/git/ci/df71e85a540429bf18ff04a08d5c0fba1ca82219/).

Looks like the original commit of pulse.el into emacs (http://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/cedet/pulse.el?id=666fd2cc6572fddd8a9a021b0359c651ac73a32d) omitted the code in question due to use of advice in related functions, and a followup q about the possibility of re-adding the functionality met with radio silence (http://thread.gmane.org/gmane.emacs.devel/115723/focus=115959).

Closing this pull request unmerged.

**Comment by abingham** [comment]
Cool, thanks for taking the time to look into this. Honestly I've never used the ycmd-pulse module and don't know if it even works!

**Comment by fischman** [comment]
Do you mean "ycmd-next-error" when you say "ycmd-pulse"?   I use y-n-e
daily and it works well for me, but IDK what ycmd-pulse is :)

**Comment by abingham** [comment]
Yes, right, I meant ycmd-next-error. Typing too fast!

**Pull request closed without merging**
