### PR TITLE
Remove duplicate function signatures from completion list.

### LINKED ISSUE #158: Duplicate entries in code completion
When having a class with virtual functions that is overridden, I see duplicate entries in the code completion
f() const -> bool [f]
f() const -> bool [f]

Works in vim+ycm.

### PR DESCRIPTION
**Pull request by ptrv**
Fixes #158

### CODE REVIEW

**Comment by abingham** [comment]
Thanks for sorting this out so quickly!

**Comment by r4nt** [comment]
Btw, do we know why this is necessary? @Valloric  said that vim-ycm does not do any deduplication - so how do those turn up there in the first place?

**Comment by Valloric** [comment]
I second @r4nt's question. I checked and couldn't find any dedup logic in YCM and I also didn't see any duplicates being shown to the user.

**Comment by Valloric** [comment]
[Here's the relevant code in ycmd](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L160). You can see that duplicates are being skipped by checking the `seen_data` map. Overloads are added as `detailed_info_`, not as extra entries.

So this is very unlikely to be a ycmd bug since it is ensuring that no duplicates are sent back. It seems to be caused by something else on the client side.

Deduping this client-side could be a possibly expensive operation, especially given that it shouldn't be necessary.

**Comment by ptrv** [comment]
It's not a bug in in `ycmd`. In `company-ycmd` we split the `detailed_info` for a completion candidate into separate entries in order to show all overloads in the completion list. In `detailed_info` there might be duplicate entries for overloads as stated in the last reply. There is the option in `company-ycmd-insert-arguments` which inserts the function arguments as template after completion. For this feature it is nice to have all overloads when completing. When setting this variable to nil you will be presented with only one overload of a function using only the content from `insertion_text`. AFAIK this is how vim+ycm showing the completion candidates and there is no need for further deduplication.

**Pull request merged**
