### PR TITLE
Add support for typescript

### PR DESCRIPTION
**Pull request by ptrv**

### CODE REVIEW

**Comment by abingham** [comment]
It looks like this needs a merge.

**Comment by ptrv** [comment]
Ok, yes. I'm on it

**Comment by ptrv** [comment]
@abingham I rebase this branch onto master. Let's wait for travis to finish

**Comment by vheon** [comment]
> Let's wait for travis to finish

Just FYI we use http://homu.io/ exactly for that, basically you tell `homu` "merge this PR" and it will first fire the test suite and then **only** if the tests passes the PR will be merged ;)

**Comment by abingham** [comment]
@vheon Oooh, I like that. I used a similar workflow at a previous employer, and it was a real joy to work with. Thanks for pointing that out.

**Pull request merged**
