### PR TITLE
Add support for objc annotation in company-ycmd

### PR DESCRIPTION
**Pull request by ptrv**
Untested.

### CODE REVIEW

**Comment by ptrv** [comment]
Do not merge! The code is untested. Let's wait for confirmation from #248

**Comment by chaozhn** [comment]
@ptrv I download company-ycmd.el file and override my existing one and relaunch Emacs, but seems it still can't show function parameters in completion tip window. Is there any switch need to be turned on? Thanks

**Comment by ptrv** [comment]
@chaozhn  Can you post a minimal example in order to reproduce the problem?

I would be nice to have the output of the ycmd server to see the json response. For this, you can set `(setq ycmd--log-enabled t)`, open your ObjC file and trigger the completion tooltip where you expect completion with function arguments. Then go to  buffer `*ycmd-content-log*` and copy its content here.

Then we can probably say more about what's not working.

**Comment by ptrv** [comment]
@chaozhn Are you sure you are triggering semantic completion and not only identifier completion?

**Comment by chaozhn** [comment]
@ptrv I will paste ycmd-log and my configuration later! thanks!

**Comment by chaozhn** [comment]
1. Here is my configuration:
````
(defun my-ycmd-config ()
  ;; ycmd setting
  (setq ycmd--log-enabled t)
  ;(setq ycmd-force-semantic-completion t)
  (cond
   ;; Mac OS
   ((spacemacs/system-is-mac)
    (set-variable 'ycmd-server-command '("python" "/Users/chao/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd"))
    (set-variable 'ycmd-global-config "/Users/chao/.ycm_extra_conf.py")
   )
   ;; Linux
   ((spacemacs/system-is-linux)
    (set-variable 'ycmd-server-command '("python" "/home/chao/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd"))
    (set-variable 'ycmd-global-config "/home/chao/.ycm_extra_conf.py")
    )
  )
  (ycmd-mode)

  ; company-ycmd settings
  (company-ycmd-setup)
  (company-quickhelp-mode 1)
  (custom-set-variables
   '(company-require-match nil)
   '(company-auto-complete nil)
   '(company-idle-delay 0)
   '(company-show-numbers t)
   '(company-tooltip-minimum-width 50)
   '(company-minimum-prefix-length 1)
  )

  ; flycheck settings
  (flycheck-ycmd-setup)
  )
````
I use spacemacs, so I added **add-hook** this for objc-mode in **dotspacemacs/init()** function.
This is ycmd-content-log

And this is my screenshot:
no-fucntion-parameters

Thanks a lot!

**Comment by ptrv** [comment]
Hi @chaozhn 

Thanks for providing the information. I've tested `company-ycmd` if we parse the data coming from `ycmd` correctly and it looks like it should work to show function parameters.

Looking at your screenshot it still looks like you are not using the updated `company-ycmd.el` from this PR. When you have overwritten the file did you check if there was also a `compant-ycmd.elc` file and deleted it? It might be that you are still using the byte-compiled version of `company-ycmd`.

Can you please check if you have still a `company-ycmd.elc`?

**Comment by chaozhn** [comment]
@ptrv Yes, you're right, I forgot delete the old *.elc. It's working now. Thanks.
If possible, I think we can improve it from some aspects:
````
[self handleAudioStreamPackets::(UInt32) NumberPackets:(UInt32) InputData:(const void *) PacketDescriptions:(AudioStreamPacketDescription *)
````
1. A redundant **:** is appeared after the function name, the problem is also existed in completion tip window.
2. When I select one function in completion tip window and click **RET** to use, the function parameters will be inserted with its name, I'm not sure if there is a configuration to control it, I just think the behaviour is different with vim. In vim, when you do these steps, only the function will be inserted and the completion window will be kept showing and you can continue to input your parameters following the function definition. If the completion window is closed, you still can see it's definition in a buffer window. I think this is really helpful for developer. I'm not sure if the **completion** plugin has same functions.(I'm a  newbie on Emacs)
3. Another phenomenon, when I input **[s**, the completion window won't show, but if I continue to input **e**, it will pop up and **self** is in the first recommendation, and then, if I continue to input **l**, in theory, the recommendation should not change, but actually, it changed, and the **self** is at the second position. I'm not sure if you can reproduce in your environment.
Thanks again!

**Comment by ptrv** [comment]
Hi @chaozhn 

I am glad that you got the changes from this PR working.

To answer your questions:

1. I noticed this too. The server is providing this, so I am not sure whether it is a bug on the server side or we as client should handle this and remove the trailing `:`. I asked the question in the `ycmd` project. See: https://github.com/Valloric/ycmd/issues/294
Let's see what the response will be

2. Inserting the function parameters as templates is a feature. You can control this by setting the variable `company-ycmd-insert-arguments` to `nil`. But on the other hand you won't see the arguments. The behavior you described for vim, does not exist in `company-mode` as far as I know.

3. Since I don't ahve access to a Mac at the moment, I cannot reproduce this. But from what you describe it may be how `ycmd` is providing the results and it is not a "bug" in `emacs-ycmd`. This would need more investigations with a working ObjC environment.

As soon as we have a clear idea about the trailing `:` I'll fix it accordingly.

**Comment by ptrv** [comment]
Hi @chaozhn 

I improved the objc completion a bit. We remove now the trailing `:`. 

Expanding parameter should also works. There was an error in the post-completion code so that's why you had incorrect behavior after completion (list item 2.) Please try out again by setting `company-ycmd-insert-arguments` to `t`.

**Comment by ptrv** [comment]
@chaozhn Did you have a chance to test the latest version of the `company-ycmd.el` file from this PR?

**Comment by ptrv** [comment]
@abingham Can we merge this? Still waiting for @chaozhn to reply but he confirmed this patch to be working and I implemented and tested his improvement list.

**Comment by abingham** [comment]
Done!

**Pull request merged**
