### PR TITLE
Minor README formatting update.

### PR DESCRIPTION
**Pull request by ptrv**

### CODE REVIEW

**Comment by ptrv** [comment]
@zzbot r+

**Comment by Valloric** [comment]
@ptrv Something is broken here. Zzbot will respond within seconds to commands. Looking at [your queue](http://35.185.255.222:54856/queue/EmacsYcmd), it doesn't see this PR as being approved or pending.

@abingham Can you confirm successful webhook delivery to homu? You should be able to see it on the page (at the bottom) where you configured it.

**Comment by abingham** [comment]
> Can you confirm successful webhook delivery to homu?

I see the initial failed delivery (i.e. before the homu endpoint was active), 30 to 40 successful calls between 22:41 and 23:20 CEST on 14.5, 3 failed calls in a row between 23:21 and 23:26, then about 15 successes up to 00:42 on 15.5.

> Also verify that you've set up delivery of events: Issue Comment, Pull Request, Push, Status.

Those are all active (and they're the only active ones).

**Comment by abingham** [comment]
@Valloric @ptrv I do see that @zzbot has not accepted my invitation to be a collaborator:
screen shot 2017-05-15 at 07 59 43

Could this be the issue?

**Comment by Valloric** [comment]
@abingham That is indeed the issue, my bad! Try using at-zzbot r+ again.

**Comment by abingham** [comment]
@zzbot r+

**Comment by ptrv** [comment]
@Valloric @abingham Nice, it works

**Comment by abingham** [comment]
Super cool! I had a gerrit/jenkins workflow at my last proper job that worked like this, and I loved it. Thanks again for helping set this up.

**Comment by Valloric** [comment]
Happy to help! :)

**Pull request merged**
