### PR TITLE
Add ycmd menu entry

### PR DESCRIPTION
**Pull request by ptrv**
Being able to run ycmd commands from the menu entry improves accessibility for users who use the mouse a lot.

### CODE REVIEW

**Comment by abingham** [comment]
Could we put this in a separate file? I feel like ycmd.el is big enough already, and this seems pretty easy to split out.

**Comment by ptrv** [comment]
I would keep this in the main file since it belongs to all the code that sets up the minor mode. I think there are definitely bigger chunks of code there which could go into separate files like the keywords or goto or fixits.

**Comment by abingham** [comment]
Good point. Thanks for doing this!

**Comment by ptrv** [comment]
Cool, thanks for merging. I'll look into trying to split out parts of `ycmd.el` into separate files

**Pull request merged**
