### PR TITLE
Add ycmd-server-command example

### PR DESCRIPTION
**Pull request by rongyi**

### CODE REVIEW

**Comment by vheon** [comment]
Why would you install YouCompleteMe (the vim client)  rather than ycmd alone?

**Comment by ptrv** [comment]
I agree with @vheon 

We should rather add an example how to use and set variables for a standalone `ycmd`

@rongyi Do you want to update the PR with an example how to setup a standalone `ycmd`?

**Comment by abingham** [comment]
I don't mind having an example like this in the documentation, but I think it should be made clear that it's non-standard.

**Comment by rongyi** [comment]
I just want readme to be more friendly, either for an Emacs user who has vim background(like me) or a pure Emacs user. I will close this PR and create a new PR which has a standalone ycmd example.

**Pull request closed without merging**
