### PR TITLE
Use package let-alist to silence warnings and simplify code

### PR DESCRIPTION
**Pull request by ptrv**
Use let-alist instead of binding all variables when parsing ycmd result
structures. let-alist binds only variables which are used in body.

This makes the code a bit simpler because we don't need to bind all variables from result manually.

### CODE REVIEW

**Comment by ptrv** [comment]
See travis: https://travis-ci.org/ptrv/emacs-ycmd/builds/117146888

**Comment by ptrv** [comment]
btw, `let-alist` is a builtin package in Emacs 25 and available from GNU Elpa for compatibility for older Emacsen.

**Comment by ptrv** [comment]
With these changes the there are no more byte-compiler warnings anymore when compiling all `.el` files.

**Comment by abingham** [comment]
That's really beautiful :)

**Pull request merged**
